export enum GENRE_NAME {
  Action = 'Action',
  Adventure = 'Adventure',
  Animation = 'Animation',
  Comedy = 'Comedy',
  Crime = 'Crime',
  Documentary = 'Documentary',
  Drama = 'Drama',
  Family = 'Family',
  Fantasy = 'Fantasy',
  History = 'History',
  Horror = 'Horror',
  Music = 'Music',
  Mystery = 'Mystery',
  Romance = 'Romance',
  ScienceFiction = 'Science Fiction',
  TVMovie = 'TV Movie',
  Thriller = 'Thriller',
  War = 'War',
  Western = 'Western',
}

export enum GENRE_ID {
  Action = '28',
  Adventure = '12',
  Animation = '16',
  Comedy = '35',
  Crime = '80',
  Documentary = '99',
  Drama = '18',
  Family = '10751',
  Fantasy = '14',
  History = '36',
  Horror = '27',
  Music = '10402',
  Mystery = '9648',
  Romance = '10749',
  ScienceFiction = '878',
  TVMovie = '10770',
  Thriller = '53',
  War = '10752',
  Western = '37',
}

export enum KEY {
  MOVIE = 'movie',
  TRAILER = 'trailer',
  BACKDROP = 'backdrop',
  LOGO = 'logo',
  POSTER = 'poster',
  CERTIFICATE = 'certificate',
  CREDITS = 'credits',
  SIMILAR = 'similar',
  POPULAR = 'popular',
  COLLECTION = 'collection',
}
