import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Suspense } from 'react'

import MovieModal from '@/core/components/modal/ index'
import Providers from '@/core/contexts'
import '@/core/styles/globals.css'
import { ChildrenProp } from '@/core/types/react'

import Navbar from './_components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Netflix Clone | @jazztinecruz',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: ChildrenProp) => {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-primary text-white`}>
        <main>
          <Providers>
            {children}
            <Suspense>
              <MovieModal />
            </Suspense>
          </Providers>
        </main>
      </body>
    </html>
  )
}

export default RootLayout
